name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: rule
        path: dist/
